import Modal from "@/components/Modal";
import "./globals.css";
// All commented code were the original default template created by create-next-app
import type { Metadata } from "next";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: "Trello React clone",
  description: "A trello clone made in React by RCCC.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      {/* Here, we only leave the children which is essentially where our page is rendered into the layout itself. */}
      <body className="bg-[#F5F6F8]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
